import { Task, Question } from '@/lib/types';

// Mock data
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    name: 'Math Practice',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'math',
    curriculum: 'american',
    questions: ['q1', 'q2', 'q3'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'task-2',
    name: 'English Assessment',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'english',
    curriculum: 'american',
    questions: ['q4', 'q5'],
    status: 'completed',
    results: {
      score: 2,
      total: 2,
      answers: {
        'q4': '32',
        'q5': 'London',
      },
    },
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: 'math-1',
    name: 'Addition and Subtraction',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'math',
    curriculum: 'american',
    questions: ['q1', 'q2', 'q6'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'french-1',
    name: 'Basic Vocabulary',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'french',
    curriculum: 'american',
    questions: ['q7', 'q8', 'l1', 'l2', 'l3', 'l4'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'science-2',
    name: 'Plant Life Cycle',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'science',
    curriculum: 'american',
    questions: ['q9', 'q10'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'english-1',
    name: 'Reading and Comprehension',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'english',
    curriculum: 'american',
    questions: ['r1', 'r2', 'r3', 'r4', 'r5'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'social-1',
    name: 'World Geography',
    childId: 'child-1',
    assignedById: 'parent-1',
    assignedByRole: 'parent',
    subject: 'social_studies',
    curriculum: 'american',
    questions: ['s1', 's2', 's3', 's4', 's5'],
    status: 'pending',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    curriculum: 'american',
    subject: 'math',
    text: 'What is 5 + 7?',
    type: 'multiple_choice',
    options: ['10', '11', '12', '13'],
    correctAnswer: '12',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q2',
    curriculum: 'american',
    subject: 'math',
    text: 'What is 8 x 4?',
    type: 'multiple_choice',
    options: ['24', '28', '32', '36'],
    correctAnswer: '32',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q3',
    curriculum: 'american',
    subject: 'science',
    text: 'The Earth revolves around the ______.',
    type: 'fill_blank',
    correctAnswer: 'Sun',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q4',
    curriculum: 'american',
    subject: 'science',
    text: 'Water freezes at 0 degrees Celsius.',
    type: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'True',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q5',
    curriculum: 'england',
    subject: 'english',
    text: 'Which of these is a proper noun?',
    type: 'multiple_choice',
    options: ['chair', 'happiness', 'London', 'beautiful'],
    correctAnswer: 'London',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q6',
    curriculum: 'american',
    subject: 'math',
    text: 'Is 10 greater than 5?',
    type: 'yes_no',
    options: ['Yes', 'No'],
    correctAnswer: 'Yes',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q7',
    curriculum: 'american',
    subject: 'french',
    text: 'Listen to the audio and write the French word for "hello".',
    type: 'listening',
    correctAnswer: 'bonjour',
    audioUrl: 'https://example.com/audio/bonjour.mp3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q8',
    curriculum: 'american',
    subject: 'french',
    text: 'Fill in the blank: Je _____ étudiant.',
    type: 'fill_blank',
    correctAnswer: 'suis',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q9',
    curriculum: 'american',
    subject: 'science',
    text: 'Please read the following passage about plant growth and record your reading.',
    type: 'reading',
    correctAnswer: '',
    storyText: 'Plants need sunlight, water, and nutrients from the soil to grow. The process of photosynthesis allows plants to convert sunlight into energy.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q10',
    curriculum: 'american',
    subject: 'science',
    text: 'What do plants need to grow?',
    type: 'multiple_choice',
    options: ['Only water', 'Only sunlight', 'Sunlight, water, and nutrients', 'Only carbon dioxide'],
    correctAnswer: 'Sunlight, water, and nutrients',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q11',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'Read the following story about world geography and answer the question: What is the largest continent?',
    type: 'learning_from_story',
    storyText: 'Earth has seven continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America. Asia is the largest continent by both land area and population.',
    options: ['Africa', 'Europe', 'Asia', 'North America'],
    correctAnswer: 'Asia',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l1',
    curriculum: 'american',
    subject: 'french',
    text: 'Listen to the audio lesson about French greetings and answer: Which greeting is used in formal settings?',
    type: 'listening',
    audioUrl: 'https://example.com/audio/french-greetings.mp3',
    options: ['Salut', 'Bonjour', 'Bonsoir', 'Enchanté'],
    correctAnswer: 'Enchanté',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l2',
    curriculum: 'american',
    subject: 'french',
    text: 'After listening to the audio about French numbers, fill in the blank: The French word for the number ten is _____.',
    type: 'listening',
    audioUrl: 'https://example.com/audio/french-numbers.mp3',
    correctAnswer: 'dix',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l3',
    curriculum: 'american',
    subject: 'french',
    text: 'Listen to the audio about French culture. Is Paris the capital of France?',
    type: 'listening',
    audioUrl: 'https://example.com/audio/french-culture.mp3',
    options: ['Yes', 'No'],
    correctAnswer: 'Yes',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l4',
    curriculum: 'american',
    subject: 'french',
    text: 'After listening to the audio about French food, is the statement true or false: "Baguette is a type of French cheese."',
    type: 'listening',
    audioUrl: 'https://example.com/audio/french-food.mp3',
    options: ['True', 'False'],
    correctAnswer: 'False',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r1',
    curriculum: 'american',
    subject: 'english',
    text: 'Read the following paragraph out loud and record your reading.',
    type: 'reading',
    storyText: 'The boy walked slowly through the forest, listening to the birds singing in the trees. He could hear the sound of a stream nearby and decided to follow it. As he reached the water, he saw a small boat tied to a tree. He wondered who it belonged to and where they might have gone.',
    correctAnswer: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r2',
    curriculum: 'american',
    subject: 'english',
    text: 'After reading the paragraph, where did the boy find the boat?',
    type: 'multiple_choice',
    options: ['In the forest', 'By the stream', 'At his home', 'On the mountain'],
    correctAnswer: 'By the stream',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r3',
    curriculum: 'american',
    subject: 'english',
    text: 'Fill in the blank: The boy could hear the sound of a _____ nearby.',
    type: 'fill_blank',
    correctAnswer: 'stream',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r4',
    curriculum: 'american',
    subject: 'english',
    text: 'Is the following statement true or false: "The boy found a bicycle by the stream."',
    type: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'False',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'r5',
    curriculum: 'american',
    subject: 'english',
    text: 'Did the boy know who owned the boat?',
    type: 'yes_no',
    options: ['Yes', 'No'],
    correctAnswer: 'No',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's1',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'Read the following story about world geography and answer the questions that follow.',
    type: 'learning_from_story',
    storyText: 'The world is divided into seven continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America. Each continent has unique geographical features, climates, and cultures. Asia is the largest continent by both land area and population, while Antarctica is the coldest and has no permanent human residents. The Pacific Ocean is the largest ocean, covering more area than all the continents combined.',
    correctAnswer: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's2',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'According to the story, which is the largest continent?',
    type: 'multiple_choice',
    options: ['Africa', 'Antarctica', 'Asia', 'Australia'],
    correctAnswer: 'Asia',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's3',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'Fill in the blank: The _______ Ocean is the largest ocean in the world.',
    type: 'fill_blank',
    correctAnswer: 'Pacific',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's4',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'True or False: Antarctica has many permanent human residents.',
    type: 'true_false',
    options: ['True', 'False'],
    correctAnswer: 'False',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's5',
    curriculum: 'american',
    subject: 'social_studies',
    text: 'Are there exactly seven continents in the world?',
    type: 'yes_no',
    options: ['Yes', 'No'],
    correctAnswer: 'Yes',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];
