// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrhqfoomuoeqwmwjhdoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaHFmb29tdW9lcXdtd2poZG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTI3MjIsImV4cCI6MjA1Nzk2ODcyMn0.euvtpexmQ3XpTCqQOiKJmAfl8UgBX4l7yCdaxOl5CCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);